### ISSUE TITLE
Multiple players using discord cannot hear each other

### ISSUE THREAD

**Issue by fennecr** [naturecodevoid/voicechat-discord#1]

**Comment by fennecr** [comment]
Is it possible to trick Simple Voice Chat into thinking discord users have the mod on their client?

**Comment by naturecodevoid** [comment]
I'm not really sure what you mean. Players that use the `/startdiscordvoicechat` command should appear as speaking. Is there an issue with multiple bots?

**Comment by naturecodevoid** [comment]
Hey, I made a small oversight when adding multiple bots functionality. The issue with multiple bot users not being able to hear each other should be fixed, could you try using the latest version (1.2.0) from https://modrinth.com/mod/simple-voice-chat-discord-bridge/versions and tell me if it fixed the problem or not?

**Comment by fennecr** [comment]
Yes, it works now!

**Comment by fennecr** [comment]
Sorry to reopen this so quickly, but it appears that after a player dies, nobody can hear them anymore?

**Comment by naturecodevoid** [comment]
Hm ok, I'm going to move that to a new issue but I'll work on investigating that.
