### ISSUE TITLE
Bot does not relay audio to discord

### ISSUE THREAD

**Issue by Rattle189** [naturecodevoid/voicechat-discord#10]
I'm running paper-1.4.0 on a Paper 1.19.3 (build 431) server with Simple Voice Chat 1.1.9.3-2.3.28 alongside Simple Voice Chat Interaction 1.19.3-1.0.3 and I've ensured that players and the bot itself have the appropriate permissions.

I can hear those talking in the Discord voice channel, however, when I try to speak, the bot does not relay back what I've said in-game.  I've tested this as a normal player and server operator but to no avail.

My server logs seem to show no issues or errors related to the plugins, which adds more to the confusion.

The mod's description states that it _allows for players without the mod to hear and _speak._ but maybe I'm misunderstanding that it's not supposed to be a two-way communications plugin?

**Comment by naturecodevoid** [comment]
It is a 2 way communication plugin. Could you double check that there are no errors? They might just be 1 line in the logs. Also, what happens if someone else uses the plugin?

**Comment by thienthan21501** [comment]
I'm running paper-1.4.0 on a Paper 1.19.3 (build 431) server with Simple Voice Chat 1.1.9.3-2.3.28 alongside Simple Voice Chat Interaction 1.19.3-1.0.3 and I've ensured that players and the bot itself have the appropriate permissions.

discord can't hear me sound from Minecraft

**Comment by naturecodevoid** [comment]
anything in console? are you sure the other players have started a discord voicechat session?

**Comment by thienthan21501** [comment]
now repeat connect and disconnect

**Comment by naturecodevoid** [comment]
closing as invalid, please try a new nightly build or 2.0.0
