### ISSUE TITLE
Bot continuously leaves and rejoins

### ISSUE THREAD

**Issue by Kxsumi** [naturecodevoid/voicechat-discord#11]
Everytime a player does "/startdiscordvoicechat" the bot will join the voice channel, but will continuously leave and join over and over.

**_Edit by @naturecodevoid: please see https://github.com/naturecodevoid/voicechat-discord/issues/11#issuecomment-1544799735_**

**Comment by naturecodevoid** [comment]
please send logs

**Comment by Kxsumi** [comment]
> please send logs

I would but there isn't much to send. Here's my latest.log.
https://mclo.gs/0BzglbP

**Comment by naturecodevoid** [comment]
I'll ask if any simple voice chat updates will have broken it. I'm currently occupied with other projects, but if I'm not busy, I can continue working on 1.5.0 and investigating the issues next weekend.

**Comment by nitrousgranola** [comment]
Can also confirm this issue. 
Here's my latest.log: https://mclo.gs/xxlNEWU

**Comment by spookyX01** [comment]
I also have this bug, if you plan on fixing this bug and haven't been able to recreate it I can give you access to my linux ubuntu

**Comment by Kxsumi** [comment]
> I also have this bug, if you plan on fixing this bug and haven't been able to recreate it I can give you access to my linux ubuntu

Don't worry they know already

**Comment by Kxsumi** [comment]
Closing this for now as it's known by the dev. Please refer to [https://github.com/naturecodevoid/voicechat-discord/issues/12](url) for more insight.

**Comment by naturecodevoid** [comment]
why would you close it? it's not fixed yet

**Comment by Kxsumi** [comment]
> why would you close it? it's not fixed yet

Good point, just remembered it disappears if it is closed. My bad!

**Comment by naturecodevoid** [comment]
This is an SSL issue that occurs JDA tries to connect to Discord through WebSocket. Here are some ways you might be able to solve it:

1. Make sure you have updated Java. If the issue still persists, try installing Java from <https://adoptium.net>. If this still doesn't fix the issue, try installing a Java build from another vendor. (If you find one that works for you, please comment here with a link!)

2. If you are on Simple Voice Chat Discord Bridge 1.5.0 or higher, add this to the command you use to start the server: `-Djda.disablessl=true`. **This must go before the `-jar` part.** Example: `java -Djda.disablessl=true -jar server.jar`

Let me know if this helps anyone.

**Comment by imcommonsense** [comment]
> **Note: it may also be a JDA bug. In this case, you won’t be able to fix it without me updating the mod. Until then, you can try a nightly build: https://github.com/naturecodevoid/voicechat-discord/actions/workflows/nightly.yml. However, nightly builds may be extremely buggy! Use at your own risk.**
> 
> This seems to be an SSL issue that occurs JDA tries to connect to Discord through WebSocket. Here are some ways you might be able to solve it:
> 
>     1. Make sure you have updated Java. If the issue still persists, try installing Java from https://adoptium.net. If this still doesn't fix the issue, try installing a Java build from another vendor. (If you find one that works for you, please comment here with a link!)
> 
>     2. If you are on Simple Voice Chat Discord Bridge 1.5.0 or higher (or using a recent nightly build), add this to the command you use to start the server: `-Djda.disablessl=true`. **This must go before the `-jar` part.** Example: `java -Djda.disablessl=true -jar server.jar`
> 
> 
> Let me know if this helps anyone.

No luck sadly. Nightly builds don't seem to work, although with a different issue. (See #18)

**Comment by DeathAngel137** [comment]
I also have the same issue

**Comment by DeathAngel137** [comment]
How do I do the 2nd fix if i use a hosting service like ploudOS?

**Comment by ChrissW-R1** [comment]
This issue still exists in the latest version 2.1.1.
All solutions in this thread doesn't fix it.

**Comment by quatr3ll** [comment]
I confirm this problem, all methods from this issue dont help

**Comment by naturecodevoid** [comment]
A 3.0.0 beta build that fixes this is available at https://github.com/naturecodevoid/voicechat-discord/actions/runs/9744638041

**Comment by naturecodevoid** [comment]
3.0.0 is now out, which fixes this issue.

Paper/Purpur: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/3.0.0
Fabric: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/zQYUpUdg
