### ISSUE TITLE
how do i compile?

### ISSUE THREAD

**Issue by spookyX01** [naturecodevoid/voicechat-discord#14]
sorry, im not good at this. im trying to compile the wip branch for 1.5.0 however whenever i run the bat or open cmd it results in build failed

**Comment by naturecodevoid** [comment]
use nightly build: https://github.com/naturecodevoid/voicechat-discord/actions/runs/4533289981

please know that you will probably have either the same issues as before or even more issues since it seems there are some bugs with the internal changes I made
