### ISSUE TITLE
[NIGHTLY] Unable to start discord voice chat.

### ISSUE THREAD

**Issue by imcommonsense** [naturecodevoid/voicechat-discord#18]
Title says it all. When attempting to start a voice chat on the 2 most recent nightly build, using their respective versions of the commands, nothing happens. No response from the console, bots don't do anything, no response in chat. 
While the command works on the release build, the bot does exactly what's stated in #11 
I have also tried both of the potential fixes in said issue thread with no results.

Any help? 
![image](https://github.com/naturecodevoid/voicechat-discord/assets/66176496/1b3225b5-0886-4a24-a897-ec0a9486c3e4)

**Comment by naturecodevoid** [comment]
this is when debug logging would be very helpful, I have no idea what it's getting stuck on. Does it say to join the VC in chat, or does it say logging into the bot?

**Comment by imcommonsense** [comment]
> this is when debug logging would be very helpful, I have no idea what it's getting stuck on. Does it say to join the VC in chat, or does it say logging into the bot? (not console, from the players view)

good point mate, give me a minute. i'll enable debug logging.

**Comment by imcommonsense** [comment]
there is absolutely no response at all.
it's clearly a recognized command, as it doesn't tell me to type /help.

quick video (uploaded to discord due to github file size restrictions.) [Link](https://cdn.discordapp.com/attachments/1077065243005558784/1109257849160347668/2023-05-19_19-12-07.mp4)

**Comment by naturecodevoid** [comment]
ah, then it's an issue with the new command system. yeah, there's no debug logging, sorry if that wasn't clear, I was more saying that I needed to implement it soon.

**Comment by imcommonsense** [comment]
> are you on fabric? I never tested it on there.

I am running Purpur 1.19.4, Latest build.

**Comment by naturecodevoid** [comment]
Oh, I know why. The new command is /dvc.

**Comment by imcommonsense** [comment]
> using their respective versions of the commands, nothing happens.

Not it, i tried dvc too.

**Comment by imcommonsense** [comment]
Please reopen this issue. It is still ongoing and has not been solved.

**Comment by imcommonsense** [comment]
UPDATE: The nightly build seems to work on 1.19.2 Purpur (I had to switch to due to plugin compatibility.) Still believe it's worth looking into however.

**Comment by naturecodevoid** [comment]
> Please reopen this issue. It is still ongoing and has not been solved.

You can also reopen it

**Comment by Kxsumi** [comment]
SVC dependency is on 1.19.2. Also it seems to get stuck on 1.19.3/1.19.4 on the bot startup. I don't think it's a plugin thing directly, but the bots are not turned on when the server starts. I'm gonna debug inside of IntelliJ now.

**Comment by Kxsumi** [comment]
Update: I got an error in my debugging process.
![image](https://github.com/naturecodevoid/voicechat-discord/assets/96434998/cc456afa-efd1-42b3-a8c1-0bfda42ae481)

**Comment by naturecodevoid** [comment]
will be fixed once Totobird's PR is merged
