### ISSUE TITLE
Unable to hear players after they die

### ISSUE THREAD

**Issue by naturecodevoid** [naturecodevoid/voicechat-discord#2]
https://github.com/naturecodevoid/voicechat-discord/issues/1#issuecomment-1336269324

**Comment by naturecodevoid** [comment]
@fennecr Just making sure, this only happens with players using voice chat through discord, right?

**Comment by fennecr** [comment]
Yes, it only affects players using discord

**Comment by naturecodevoid** [comment]
Alright, I didn't encounter this in my initial testing (players using discord died many times but we could always hear them afterwards) but it may be related to 1.1.0 or 1.2.0 changes. Are you using Fabric or Paper? I'll do some testing when I get some free time in the next day or two.

**Comment by fennecr** [comment]
I'm using Fabric/Quilt, I am also using a lot of other mods, so it could be one of them causing it. I realize it happens after a player dies and is teleported back to our testing area, so it might be a teleportation issue and not a death issue.

**Comment by naturecodevoid** [comment]
I was able to reproduce the issue, but I think it may be a bug with Simple Voice Chat itself so I'm currently waiting to hear back from its developers.

**Comment by naturecodevoid** [comment]
Turns out it was both a Simple Voice Chat bug and a bug with the discord bridge plugin, but it should be fixed in 1.3.0.
