### ISSUE TITLE
1.20 version

### ISSUE THREAD

**Issue by onebeastchris** [naturecodevoid/voicechat-discord#20]
When attempting to start the fabric version of this plugin, you get a version error. I've tried to simply bump the required fabric version, but that just spits out a different (sort of confusing) error about the simple voice chat dependendency:
https://paste.gg/p/anonymous/8c908f2bf98f4065b2d09888388aa8d8
Not sure what the issue would be here.

**Comment by naturecodevoid** [comment]
Oops, that's an issue with one of the more recent changes I made.

**Comment by naturecodevoid** [comment]
Should be fixed with the next nightly build

**Comment by onebeastchris** [comment]
Thank you!
