### ISSUE TITLE
PurpurMC Loud static / glitchy noise through bot

### ISSUE THREAD

**Issue by frizzbees** [naturecodevoid/voicechat-discord#22]
**Describe the bug**
Users speaking to eachother through the mod in game, and users speaking to the discord bot all produce clear audio. The issue is that any audio the bot forwards to the voice channel has very loud static and cuts out frequently

**To Reproduce**
1. Setup server with latest version of this plugin, simple voice chat, and [PurpurMC](https://purpurmc.org/)
2. Run /dvc start
3. Talk to person through the mod / discord bot
4. Very loud static and glitchy audio coming from the bot itself
**Expected behavior**
Expected clear enough audio both ways
**Screenshots**

**Logs**
First, set `debug_level` to `3` (or `2` if there's too much spam) in the Simple Voice Chat Discord Bridge configuration file. After restarting your server or using `/dvc reloadconfig`, please upload the server logs here (make sure they don't include any sensitive info).
(log since /dvc reloadconfig for log level 2)
https://mclo.gs/lRSx0ao

**Versions (please complete the following information):**
- Minecraft: 1.20.1
- Loader (paper, purpur, fabric, quilt, etc): purpur
- Simple Voice Chat: latest
- Simple Voice Chat Discord Bridge: latest 

**Additional context**

**Comment by naturecodevoid** [comment]
This was reported to me via DMs also. Not sure why I never encountered it during testing, I'll have to look into it on the weekend or something

**Comment by naturecodevoid** [comment]
Could you provide logs with `debug_level` set to `3`?

**Comment by naturecodevoid** [comment]
Should be fixed with 2.0.1
