### ISSUE TITLE
/dvc commands not working

### ISSUE THREAD

**Issue by AvatarMental** [naturecodevoid/voicechat-discord#25]
**Describe the bug**
Error appears when attempting to run `/dvc start`

**To Reproduce**
Join appropriate voice channel in discord.
Run `/dvc start`

**Expected behavior**
bot should join channel, but does not, instead get "Unexpected Error" message in-game. (This appears to happen with any `/dvc` command)

**Screenshots**

**Logs**
[STDERR]: java.lang.NoSuchMethodError: 'net.minecraft.class_5250 net.minecraft.class_2561$class_2562.fromJson(dev.naturecodevoid.voicechatdiscord.shadow.gson.JsonElement)'
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at dev.naturecodevoid.voicechatdiscord.FabricPlatform.toNative(FabricPlatform.java:110)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at dev.naturecodevoid.voicechatdiscord.FabricPlatform.sendMessage(FabricPlatform.java:76)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at dev.naturecodevoid.voicechatdiscord.SubCommands.start(SubCommands.java:110)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at dev.naturecodevoid.voicechatdiscord.SubCommands.lambda$wrapInTry$0(SubCommands.java:76)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.class_2170.method_9249(class_2170.java:287)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.class_3244.method_45010(class_3244.java:1341)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.class_3244.method_44356(class_3244.java:1321)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.class_1255.method_5386(class_1255.java:67)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.class_3738.run(class_3738.java:18)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.class_1255.method_18859(class_1255.java:156)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.class_4093.method_18859(class_4093.java:23)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.class_1255.method_16075(class_1255.java:130)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.class_1255.method_18857(class_1255.java:139)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.server.MinecraftServer.handler$zbh000$carpet$modifiedRunLoop(MinecraftServer.java:6451)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
22.06 12:01:29 [Server] Server thread/INFO [STDERR]: at java.base/java.lang.Thread.run(Thread.java:833)

**Versions (please complete the following information):**
- Minecraft: 1.20.1
- Loader (paper, purpur, fabric, quilt, etc): Fabric
- Simple Voice Chat:  2.4.11
- Simple Voice Chat Discord Bridge: 2.1.0

**Additional context**

**Comment by Voidlighter** [comment]
I have this very same problem, with exactly the same error
[server-exerpt.log](https://github.com/naturecodevoid/voicechat-discord/files/12644314/server-exerpt.log)

**Comment by DillonB07** [comment]
Yeah, got it here also. 1.20.1 Fabric server =/

**Comment by imcommonsense** [comment]
same here. really annoying issue.

**Comment by naturecodevoid** [comment]
Sorry everyone, this project has been pretty unmaintained since the last update since I don't really enjoy working on it with the limited free time I have. I may be able to look into this and the other issues soon.

**Comment by imcommonsense** [comment]
A temporary fix for the time being is to just downgrade to the second latest 1.20(.1) build.

**Comment by naturecodevoid** [comment]
I've identified the issue as the `fromJson` method not being remapped to intermediary mappings. I'll ask about this in the Fabric discord, but until there's an actual fix I'll just use some reflection. I will post here when a test build is ready

**Comment by naturecodevoid** [comment]
@AvatarMental @Voidlighter @DillonB07 @imcommonsense Could you see if this nightly build fixes it? https://github.com/naturecodevoid/voicechat-discord/actions/runs/6363837591

**Comment by Voidlighter** [comment]
> @AvatarMental @Voidlighter @DillonB07 @imcommonsense Could you see if this nightly build fixes it? https://github.com/naturecodevoid/voicechat-discord/actions/runs/6363837591
[2023-09-30-3.log](https://github.com/naturecodevoid/voicechat-discord/files/12775134/2023-09-30-3.log)

I tried it, but I couldn't join from Java or Bedrock to even test the command.

**Comment by naturecodevoid** [comment]
Wow, that's impressive. I'll look into why that happened. btw, I deleted your comment since the log file leaked your IP

**Comment by naturecodevoid** [comment]
@Voidlighter could you try this build? https://github.com/naturecodevoid/voicechat-discord/actions/runs/6364564383

**Comment by Voidlighter** [comment]
@naturecodevoid It worked! I tested it and everything seems to be working great.

**Comment by naturecodevoid** [comment]
Glad to hear! I am going to close this as fixed. If anyone else still has issues, please comment and I will reopen it.

I will probably create a new release sometime in the next few days after I've fixed some other issues. This might be delayed since I'm currently experimenting with using Rust to fix #11.
