### ISSUE TITLE
/dvc start not working

### ISSUE THREAD

**Issue by Warningtntman** [naturecodevoid/voicechat-discord#28]
**Describe the bug**
Getting an error and bot not joining the VC

**To Reproduce**
Start the server using Paper 1.20.1 / simple voice chat / voice chat discord

**Expected behavior**
For the bot to join VC and work

**Screenshots**
![image](https://github.com/naturecodevoid/voicechat-discord/assets/141004040/646c71db-3dcf-48ab-860a-3eed52050ffd)
![image](https://github.com/naturecodevoid/voicechat-discord/assets/141004040/f3f0eab9-894f-4bdf-b73f-09bb0a1ca674)

**Logs**
https://mclo.gs/kVmJknf

**Versions (please complete the following information):**
- Minecraft: 1.20.1
- Loader (paper, purpur, fabric, quilt, etc): paper
- Simple Voice Chat: 2.1.0
- Simple Voice Chat Discord Bridge: 2.4.15

**Comment by naturecodevoid** [comment]
Read the error message. You have SVC installed client side. If you want to test the addon, disable/uninstall SVC clientside.
