### ISSUE TITLE
Forge support

### ISSUE THREAD

**Issue by bobby365** [naturecodevoid/voicechat-discord#31]
It would be nice if this supported forge as not everyone can use fabric

**Comment by naturecodevoid** [comment]
I'm sorry but this is a hard no from me.

As far as I know, forge is a pretty big pain to develop for when compared to fabric. It seems very outdated with tons of features that aren't really used. I find it hard to believe that you can't use fabric.

That being said, the last time I used forge (and developed mods for it) was in 1.8.9. But I doubt it's any different. Fabric is just much more modern.
