### ISSUE TITLE
Server console unable to view vanilla logs

### ISSUE THREAD

**Issue by DayDarkTV** [naturecodevoid/voicechat-discord#36]
**Describe the bug**
Upon server loading with this mod, it is no longer able to view the result messages to any inputted commands.
I believe this is what is really happening in #27 
the console stops showing any output logs, but clients can connect, and using a command like the say command does still send the message to clients.

**To Reproduce**
same as #27 , load fabric api, svc, and this mod using quilt loader

**Expected behavior**
Server console should be able to view typical server logs

**Screenshots**
![image](https://github.com/naturecodevoid/voicechat-discord/assets/67245492/7942e09a-37cf-4b57-a829-05fc059edfbd)

**Logs**
Server log:
https://pastebin.com/YvaAsh13

**Versions (please complete the following information):**
- Minecraft: 1.20.4
- Loader (paper, purpur, fabric, quilt, etc): Quilt 0.23.0-beta.1
- Simple Voice Chat: 2.4.32
- Simple Voice Chat Discord Bridge: 2.1.1

**Comment by naturecodevoid** [comment]
Seems like the same issue, will close as duplicate
