### ISSUE TITLE
Corrupted Stream error everytime a discord user speaks

### ISSUE THREAD

**Issue by Mxmzeed** [naturecodevoid/voicechat-discord#37]
I was using the plugin with 4 people, me and my friend in discord and my other two friends using SVC. I could hear all of my friends and the other one using the bot too, but one of the minecraft mod users couldn't hear my friend. When I checked the console, there was a "Corrupted Stream Error"

**Expected behavior*
I never thought it would work flawlessly but I'm just trying to fix it for a minecraft event.

**Screenshots**
![image](https://github.com/naturecodevoid/voicechat-discord/assets/108960148/288ffa74-6e15-4a37-8011-b70389396c22)

**Logs**
java.lang.RuntimeException: Failed to decode audio data: An error occurred during decoding: corrupted stream
07.01 21:01:22 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.opus.JavaOpusDecoderImpl.decode(JavaOpusDecoderImpl.java:51)
07.01 21:01:22 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleOutgoingSoundPacket(DiscordBot.java:291)
07.01 21:01:22 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.PluginManager.onListenerAudio(PluginManager.java:126)
07.01 21:01:22 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.sendSoundPacket(Server.java:393)
07.01 21:01:22 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.broadcast(Server.java:442)
07.01 21:01:22 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processProximityPacket(Server.java:379)
07.01 21:01:22 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processMicPacket(Server.java:316)
07.01 21:01:22 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:303)
07.01 21:01:22 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.sendMicrophonePacket(AudioSenderImpl.java:90)
07.01 21:01:22 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.send(AudioSenderImpl.java:66)
07.01 21:01:22 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleEncodedAudio(DiscordBot.java:383)
07.01 21:01:22 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.shadow.jda.internal.audio.AudioConnection.lambda$setupReceiveThread$4(AudioConnection.java:411)
07.01 21:01:22 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
07.01 21:01:24 [Server] [INFO] NerdThree14 issued server command: /dvc togglewhisper
07.01 21:01:42 [Server] [WARN] java.lang.RuntimeException: Failed to decode audio data: An error occurred during decoding: corrupted stream
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.opus.JavaOpusDecoderImpl.decode(JavaOpusDecoderImpl.java:51)
07.01 21:01:42 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleOutgoingSoundPacket(DiscordBot.java:291)
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.PluginManager.onListenerAudio(PluginManager.java:126)
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.sendSoundPacket(Server.java:393)
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.broadcast(Server.java:442)
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processProximityPacket(Server.java:379)
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processMicPacket(Server.java:316)
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:303)
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.sendMicrophonePacket(AudioSenderImpl.java:90)
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.send(AudioSenderImpl.java:66)
07.01 21:01:42 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleEncodedAudio(DiscordBot.java:383)
07.01 21:01:42 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.shadow.jda.internal.audio.AudioConnection.lambda$setupReceiveThread$4(AudioConnection.java:411)
07.01 21:01:42 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
07.01 21:01:42 [Server] [WARN] java.lang.RuntimeException: Failed to decode audio data: An error occurred during decoding: corrupted stream
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.opus.JavaOpusDecoderImpl.decode(JavaOpusDecoderImpl.java:51)
07.01 21:01:42 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleOutgoingSoundPacket(DiscordBot.java:291)
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.PluginManager.onListenerAudio(PluginManager.java:126)
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.sendSoundPacket(Server.java:393)
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.broadcast(Server.java:442)
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processProximityPacket(Server.java:379)
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processMicPacket(Server.java:316)
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:303)
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.sendMicrophonePacket(AudioSenderImpl.java:90)
07.01 21:01:42 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.send(AudioSenderImpl.java:66)
07.01 21:01:42 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleEncodedAudio(DiscordBot.java:383)
07.01 21:01:42 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.shadow.jda.internal.audio.AudioConnection.lambda$setupReceiveThread$4(AudioConnection.java:411)
07.01 21:01:42 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
07.01 21:01:58 [Server] [INFO] NerdThree14 issued server command: /dvc togglewhisper
07.01 21:02:07 [Server] [WARN] java.lang.RuntimeException: Failed to decode audio data: An error occurred during decoding: corrupted stream
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.opus.JavaOpusDecoderImpl.decode(JavaOpusDecoderImpl.java:51)
07.01 21:02:07 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleOutgoingSoundPacket(DiscordBot.java:291)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.PluginManager.onListenerAudio(PluginManager.java:126)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.sendSoundPacket(Server.java:393)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.broadcast(Server.java:442)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processProximityPacket(Server.java:379)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processMicPacket(Server.java:316)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:303)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.sendMicrophonePacket(AudioSenderImpl.java:90)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.send(AudioSenderImpl.java:66)
07.01 21:02:07 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleEncodedAudio(DiscordBot.java:383)
07.01 21:02:07 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.shadow.jda.internal.audio.AudioConnection.lambda$setupReceiveThread$4(AudioConnection.java:411)
07.01 21:02:07 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
07.01 21:02:07 [Server] [WARN] java.lang.RuntimeException: Failed to decode audio data: An error occurred during decoding: corrupted stream
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.opus.JavaOpusDecoderImpl.decode(JavaOpusDecoderImpl.java:51)
07.01 21:02:07 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleOutgoingSoundPacket(DiscordBot.java:291)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.PluginManager.onListenerAudio(PluginManager.java:126)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.sendSoundPacket(Server.java:393)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.broadcast(Server.java:442)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processProximityPacket(Server.java:379)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processMicPacket(Server.java:316)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:303)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.sendMicrophonePacket(AudioSenderImpl.java:90)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.send(AudioSenderImpl.java:66)
07.01 21:02:07 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleEncodedAudio(DiscordBot.java:383)
07.01 21:02:07 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.shadow.jda.internal.audio.AudioConnection.lambda$setupReceiveThread$4(AudioConnection.java:411)
07.01 21:02:07 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
07.01 21:02:07 [Server] [WARN] java.lang.RuntimeException: Failed to decode audio data: An error occurred during decoding: corrupted stream
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.opus.JavaOpusDecoderImpl.decode(JavaOpusDecoderImpl.java:51)
07.01 21:02:07 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleOutgoingSoundPacket(DiscordBot.java:291)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.PluginManager.onListenerAudio(PluginManager.java:126)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.sendSoundPacket(Server.java:393)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.broadcast(Server.java:442)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processProximityPacket(Server.java:379)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processMicPacket(Server.java:316)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:303)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.sendMicrophonePacket(AudioSenderImpl.java:90)
07.01 21:02:07 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.send(AudioSenderImpl.java:66)
07.01 21:02:07 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleEncodedAudio(DiscordBot.java:383)
07.01 21:02:07 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.shadow.jda.internal.audio.AudioConnection.lambda$setupReceiveThread$4(AudioConnection.java:411)
07.01 21:02:07 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
07.01 21:02:12 [Server] [WARN] java.lang.RuntimeException: Failed to decode audio data: An error occurred during decoding: corrupted stream
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.opus.JavaOpusDecoderImpl.decode(JavaOpusDecoderImpl.java:51)
07.01 21:02:12 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleOutgoingSoundPacket(DiscordBot.java:291)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.PluginManager.onListenerAudio(PluginManager.java:126)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.sendSoundPacket(Server.java:393)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.broadcast(Server.java:442)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processProximityPacket(Server.java:379)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processMicPacket(Server.java:316)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:303)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.sendMicrophonePacket(AudioSenderImpl.java:90)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.send(AudioSenderImpl.java:66)
07.01 21:02:12 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleEncodedAudio(DiscordBot.java:383)
07.01 21:02:12 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.shadow.jda.internal.audio.AudioConnection.lambda$setupReceiveThread$4(AudioConnection.java:411)
07.01 21:02:12 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
07.01 21:02:12 [Server] [WARN] java.lang.RuntimeException: Failed to decode audio data: An error occurred during decoding: corrupted stream
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.opus.JavaOpusDecoderImpl.decode(JavaOpusDecoderImpl.java:51)
07.01 21:02:12 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleOutgoingSoundPacket(DiscordBot.java:291)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.PluginManager.onListenerAudio(PluginManager.java:126)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.sendSoundPacket(Server.java:393)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.broadcast(Server.java:442)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processProximityPacket(Server.java:379)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processMicPacket(Server.java:316)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:303)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.sendMicrophonePacket(AudioSenderImpl.java:90)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.send(AudioSenderImpl.java:66)
07.01 21:02:12 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleEncodedAudio(DiscordBot.java:383)
07.01 21:02:12 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.shadow.jda.internal.audio.AudioConnection.lambda$setupReceiveThread$4(AudioConnection.java:411)
07.01 21:02:12 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
07.01 21:02:12 [Server] [WARN] java.lang.RuntimeException: Failed to decode audio data: An error occurred during decoding: corrupted stream
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.opus.JavaOpusDecoderImpl.decode(JavaOpusDecoderImpl.java:51)
07.01 21:02:12 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleOutgoingSoundPacket(DiscordBot.java:291)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.PluginManager.onListenerAudio(PluginManager.java:126)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.sendSoundPacket(Server.java:393)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.broadcast(Server.java:442)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processProximityPacket(Server.java:379)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.processMicPacket(Server.java:316)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:303)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.sendMicrophonePacket(AudioSenderImpl.java:90)
07.01 21:02:12 [Server] [WARN] at voicechat-bukkit-2.4.29.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.send(AudioSenderImpl.java:66)
07.01 21:02:12 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleEncodedAudio(DiscordBot.java:383)
07.01 21:02:12 [Server] [WARN] at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.shadow.jda.internal.audio.AudioConnection.lambda$setupReceiveThread$4(AudioConnection.java:411)
07.01 21:02:12 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)

**Versions (please complete the following information):**
- Minecraft: 1.20.2
- Loader paper
- Simple Voice Chat: 2.4.29
- Simple Voice Chat Discord Bridge: 2.1.1

**Comment by naturecodevoid** [comment]
Never seen this error before. Will ask SVC's author

**Comment by mxmzx** [comment]
Alright, please tell me if you find anything

**Comment by naturecodevoid** [comment]
It's likely non opus data, and I have no idea why that would happen. I likely won't have time to debug this for a while (if I can even reproduce it)

**Comment by naturecodevoid** [comment]
I've been unable to reproduce this. Let me know if you still have issues after updating to 3.0.0 (currently set to release on Wednesday) and I'll reopen the issue.
