### ISSUE TITLE
Bot will not join the vc on discord

### ISSUE THREAD

**Issue by DJJoe6895** [naturecodevoid/voicechat-discord#38]
**Describe the bug**
The Bot doesn't Join the vc on Discord and when I type the /dvc start it says couldn't register an audio sender for you, this is most likely means you have the mod installed and working
![image](https://github.com/naturecodevoid/voicechat-discord/assets/157532922/92fb703c-ba08-46d0-a976-f3a9495bb1e6)

**Versions (please complete the following information):**
- Minecraft: 1.20.1
- Loader Fabric
- Simple Voice Chat: 2.4.32
- Simple Voice Chat Discord Bridge: 2.1.1

**Comment by naturecodevoid** [comment]
Did you figure it out? You just have to read the error message.
