### ISSUE TITLE
Could not register audio sender for you. This most likely means you have the mod installed and working.

### ISSUE THREAD

**Issue by ItsJonathanJ** [naturecodevoid/voicechat-discord#40]
Hello! I installed this on my server and when I run /dvc start I encounter this issue. The error message makes no sense? It doesn't tell me what's wrong. It just tells me I did it right...

I am on Fabric 1.20.4 with the voicechat 2.4.32 and the bridge 2.1.1

**Comment by naturecodevoid** [comment]
What issue? Did you mean to attach a screenshot?

**Comment by ItsJonathanJ** [comment]
> What issue? Did you mean to attach a screenshot?

The error I got was in the title. No error stack in the console, just that message in the chat when I run it.

**Comment by naturecodevoid** [comment]
Read the error. You cannot use the mod if you have Simple Voice Chat installed on your client
