### ISSUE TITLE
Couldn't register an audio sender for you. This most likely means you have the mod installed and working despite not having mod on client

### ISSUE THREAD

**Issue by SmallMarbles** [naturecodevoid/voicechat-discord#43]
so i have the SVC mod on client but not DVC, and its still telling me this.
![image](https://github.com/naturecodevoid/voicechat-discord/assets/103583937/5191d26c-c02a-4e51-bf83-2649d37aeb19)
Bot goes online, max joins gc for a few seconds and then disappears

**Comment by naturecodevoid** [comment]
Read the error message. You cannot use the addon if you have SVC installed client side.

**Comment by SmallMarbles** [comment]
Doesn't that mean I can't use the voice chat or?

**Comment by naturecodevoid** [comment]
You can’t use the functionality this addon provides if you want Simple Voice Chat installed on your client. If you uninstall or disable the mod on the client side, you will be able to use this addon.
