### ISSUE TITLE
1.20.4?

### ISSUE THREAD

**Issue by ManicQuinn** [naturecodevoid/voicechat-discord#44]
Hoping for 1.20.4 support

**Comment by naturecodevoid** [comment]
It should work fine with 1.20.4.

**Comment by naturecodevoid** [comment]
Update: https://github.com/naturecodevoid/voicechat-discord/issues/51#issuecomment-2172184678

**Comment by naturecodevoid** [comment]
Will be fixed in 3.0.0

**Comment by naturecodevoid** [comment]
3.0.0 is now out, which fixes this issue.

Paper/Purpur: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/3.0.0
Fabric: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/zQYUpUdg
