### ISSUE TITLE
SVC Plug Icon showing when discord user connects

### ISSUE THREAD

**Issue by BerryBlu** [naturecodevoid/voicechat-discord#46]
Whenever /dvc start is used and a bot is connected, players using the svc mod will receive the plug icon in the bottom left hand and their client will no longer be able to voice chat.

**To Reproduce**
1. Use /dvc start
2. have a player with svc installed
3. their voice chat will no longer work (/voicechat test <playername> yields "client not connected" message)

**Expected behavior**
Voice chat works like normal

**Screenshots**

**Logs**
 at java.lang.Thread.run(Thread.java:840) ~[?:?]
04.05 20:54:54 [Server] INFO Caused by: de.maxhenkel.voicechat.concentus.OpusException: An error occurred during decoding: corrupted stream
04.05 20:54:54 [Server] INFO at de.maxhenkel.voicechat.concentus.OpusDecoder.decode(OpusDecoder.java:699) ~[voicechat-fabric-1.20.4-2.5.12%20(2).jar:?]
04.05 20:54:54 [Server] INFO at de.maxhenkel.voicechat.plugins.impl.opus.JavaOpusDecoderImpl.decode(JavaOpusDecoderImpl.java:44) ~[voicechat-fabric-1.20.4-2.5.12%20(2).jar:?]
04.05 20:54:54 [Server] INFO ... 9 more
04.05 20:54:54 [Server] JDA AudioConnection Guild: 1233934101216759940 Receiving Thread/ERROR [voicechat] Failed to dispatch event 'MicrophonePacketEventImpl'
04.05 20:54:54 [Server] INFO java.lang.RuntimeException: Failed to decode audio
04.05 20:54:54 [Server] INFO at de.maxhenkel.voicechat.plugins.impl.opus.JavaOpusDecoderImpl.decode(JavaOpusDecoderImpl.java:47) ~[voicechat-fabric-1.20.4-2.5.12%20(2).jar:?]
04.05 20:54:54 [Server] INFO at de.maxhenkel.vcinteraction.Plugin.onMicPacket(Plugin.java:88) ~[vcinteraction-fabric-1.20.4-1.0.6.jar:?]
04.05 20:54:54 [Server] INFO at de.maxhenkel.voicechat.plugins.PluginManager.dispatchEvent(PluginManager.java:136) ~[voicechat-fabric-1.20.4-2.5.12%20(2).jar:?]
04.05 20:54:54 [Server] INFO at de.maxhenkel.voicechat.plugins.PluginManager.onMicPacket(PluginManager.java:249) ~[voicechat-fabric-1.20.4-2.5.12%20(2).jar:?]
04.05 20:54:54 [Server] INFO at de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:339) ~[voicechat-fabric-1.20.4-2.5.12%20(2).jar:?]
04.05 20:54:54 [Server] INFO at de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.sendMicrophonePacket(AudioSenderImpl.java:90) ~[voicechat-fabric-1.20.4-2.5.12%20(2).jar:?]
04.05 20:54:54 [Server] INFO at de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.send(AudioSenderImpl.java:66) ~[voicechat-fabric-1.20.4-2.5.12%20(2).jar:?]
04.05 20:54:54 [Server] INFO at dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleEncodedAudio(DiscordBot.java:383) ~[voicechat-discord-fabric-2.1.1.jar:?]
04.05 20:54:54 [Server] INFO at dev.naturecodevoid.voicechatdiscord.shadow.jda.internal.audio.AudioConnection.lambda$setupReceiveThread$4(AudioConnection.java:411) ~[voicechat-discord-fabric-2.1.1.jar:?]

**Versions (please complete the following information):**
- Minecraft: 1.20.4
- Loader (paper, purpur, fabric, quilt, etc): Fabric
- Simple Voice Chat: 2.5.13
- Simple Voice Chat Discord Bridge: 2.1.1

**Comment by naturecodevoid** [comment]
This is expected behavior, although a helpful message should appear. This plugin cannot be used by players that have SVC installed on their client.

**Comment by naturecodevoid** [comment]
Hm, actually, this might be a bigger issue. Let me know if having SVC disabled client side fixes it

**Comment by BerryBlu** [comment]
Yeah if I disable my SVC client side that would technically fix it. Is the bridge intended to communicate with the SVC mod?

**Comment by BerryBlu** [comment]
But that's only because it's SVC itself that is breaking, not DVC

**Comment by naturecodevoid** [comment]
Yes, it has to. But you can’t use DVC with SVC installed on your client (it has to be on the server though)

**Comment by BerryBlu** [comment]
Yeah but can other people? I have SVC without DVC and my friend has DVC and that's what's causing this issue. So does everyone have to only use DVC for this mod to work? or can some use SVC and others use DVC?

**Comment by naturecodevoid** [comment]
Server must have both DVC and SVC. People that want to use DVC should not have SVC installed on their client. DVC is a server sided mod, clients should not have it installed.

**Comment by BerryBlu** [comment]
Okay I think that makes sense
