### ISSUE TITLE
error when starting the service

### ISSUE THREAD

**Issue by Woodmanxd3** [naturecodevoid/voicechat-discord#47]
Error:

"Couldn't register an audio sender for you.
This most likely means you have the mod installed and working."

Server version: 1.20.4 (purpur)
Client version: 1.20.2 (fabric)

The bot is online on my discord server but does nothing.
I have already told the bot the channel id and it should have the permissions required.
The plugin commands work all but /dvc start and /dvc stop
When I do the command /dvc start it makes the bot go online but then gives me that message and does not work.
I followed the setup guide exactly, not sure what is wrong with it. Let me know if I need to send more info-

**Comment by naturecodevoid** [comment]
You must remove SVC from your client to use DVC.
