### ISSUE TITLE
Addon crashes on older versions of glibc

### ISSUE THREAD

**Issue by MQXO** [naturecodevoid/voicechat-discord#54]
**Describe the bug**
Multiple errors thrown including glibc 2.33 not found and could not load linux natives, server crashes on startup.

**To Reproduce**
1. Host a minecraft server on pebblehost, on 1.21 fabric
2. Install Fabric API, SVC and discord bridge.
3. Start server

**Expected behavior**
Server boots as normal with SVC and discord bridge running

**Logs**
https://mcpaste.io/f9b19fb04d2adb62

**Versions (please complete the following information):**
- Minecraft: 1.21
- Loader (paper, purpur, fabric, quilt, etc): Fabric
- Simple Voice Chat: 1.21-2.5.18
- Simple Voice Chat Discord Bridge: 3.0.0

**Additional context**
Server runs fine locally on Linux Mint 21.3 Cinnamon, I am guessing theres nothing you can do as it would require pebblehost to have the compatible glibc and we dont have shell access to do it ourselves. Opened a ticket with them as well to see if theres anything they can do.

**Comment by naturecodevoid** [comment]
It's possible the natives could be built for earlier glibc versions, but it would likely increase the binary size and cause other issues. Pebblehost should really be using a newer version anyways—it's in their own best interest to upgrade

**Comment by naturecodevoid** [comment]
@MQXO Actually, this should be a pretty easy fix. Can you try this nightly build? Jars will be at the bottom https://github.com/naturecodevoid/voicechat-discord/actions/runs/9797703788

**Comment by MQXO** [comment]
I'm out for a little bit today (GMT) so I'll try it this evening when I'm home, cheers

**Comment by naturecodevoid** [comment]
@MQXO Sorry to bother you, but I'm hoping to release 3.0.1 tomorrow with fixes to this and #56. Did the fix work?

**Comment by naturecodevoid** [comment]
Should be fixed in 3.0.1. Please let me know if it is or isn't fixed so I can close this issue if it is fixed

Paper: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/3.0.1
Fabric: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/WjEQeh7I

**Comment by MQXO** [comment]
Hi, sorry I had a lot of real life problems the last while, but just to let you know that thats working fine and youre all good to close the issue. Thanks a mil.

**Comment by naturecodevoid** [comment]
Good to hear! No worries 👍
