### ISSUE TITLE
Bot doesn't speak in Discord

### ISSUE THREAD

**Issue by Pranet-Bhatti** [naturecodevoid/voicechat-discord#55]
Describe the bug
When I type /dvc start is says "Couldn't register an audio sender for you. this is most likely means you have the mod installed and working."

To Reproduce
1.Join appropriate voice channel in discord.
Run /dvc start

i saw previous similar issues removed the mod from client then it does not even show the microphone icon, but starts sucessfully, ik am dum can u please make a yooutube tutorial. and showcase the mod working too in it.

**Comment by Pranet-Bhatti** [comment]
rn i have no mod in client side, and svc and this discord plugin in server side

**Comment by naturecodevoid** [comment]
So the bot isn't speaking if people speak in SVC? Does it speak if people speak in discord?

**Comment by naturecodevoid** [comment]
@Pranet-Bhatti Please make sure you are on the latest version of the addon. It seems you are on an outdated version
