### ISSUE TITLE
Bot does not disconnect from voice channel

### ISSUE THREAD

**Issue by DaddyRobLIVE** [naturecodevoid/voicechat-discord#57]
**Is your feature request related to a problem? Please describe.**
Yes, voice chat remains open even if they are no longer in use, this causes new users not to be able to create a voice chat room for them even though there are inactive rooms.

**Describe the solution you'd like**
I'd like to have a bot killer timer available in the config, for example: inactivity-timer: 5m - this automatically destroys the proximity voice room if the player who started /dvc start has been offline for more than 5mins making the room available for other people's use.

**Describe alternatives you've considered**
I've been reloading the plugin from time to time for new rooms to be generated but the problem with this is that active voice rooms will get disconnected.

**Additional context**
None, thanks for your hard work!

**Comment by naturecodevoid** [comment]
Do the players run /dvc stop or leave the game, or do they just leave the voice channel while still playing the game? If they are still playing ask them to run /dvc stop when they are done

**Comment by DaddyRobLIVE** [comment]
Most players won't bother typing /dvc stop. They will just leave the server.

My suggestion above would be a good way since it'll be a hassle to keep opening a voice room using /dvc start if you get disconnected. But having a disconnection timer is good to give them some time to reconnect to the call.

**Comment by naturecodevoid** [comment]
If they leave the server the bot should stop itself. If it doesn't, that's a bug

**Comment by naturecodevoid** [comment]
So when a player using voice chat leaves the server, does the bot leave the voice channel?

**Comment by DaddyRobLIVE** [comment]
> So when a player using voice chat leaves the server, does the bot leave the voice channel?

The bot remains.

**Comment by naturecodevoid** [comment]
Are there any logs after/before the player leaves?

**Comment by DaddyRobLIVE** [comment]
I will check the console for logs.

**Comment by naturecodevoid** [comment]
Fixed in 3.0.1.

Paper: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/3.0.1
Fabric: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/WjEQeh7I

**Comment by naturecodevoid** [comment]
If the bug fix doesn't fix the issue with you, feel free to make a feature request with the information you said earlier.

**Comment by DaddyRobLIVE** [comment]
Got it. I will check.
