### ISSUE TITLE
Bug or probably something i messed up when using /dvc start 

### ISSUE THREAD

**Issue by Kirilokaq** [naturecodevoid/voicechat-discord#62]
I don't know what to do at this point, everything in the config seems fine, and svc perfectly runs with the mod, but if a player uses /dvc start, this happens:

- [Thu 02:11:16 ERROR voicechat-discord] Failed to start voice connection for bot with vc_id 1192523736063160360: Unable to join call: failed to join voice channel: establishing connection failed: failed to connect to Discord RTP server: connection attempt timed out

I tried reinstalling the plugin, or making new bots, nothing that i try fixes this problem, really need some help here

**Comment by naturecodevoid** [comment]
Seems like your host is blocking access to Discord. Try using a plugin like DiscordSRV, if that doesn't work, talk to your host.

**Comment by Kirilokaq** [comment]
How can DiscordSRV help?

**Comment by naturecodevoid** [comment]
It won't. But since DiscordSRV talks to Discord, if it doesn't work, that means that discord is being blocked.

**Comment by Kirilokaq** [comment]
Minecraft to Discord messages in DiscordSRV are fine... Not sure about proximity voice chat though, the discordsrv bot doesn't need to join the voice channel 

But i do know, that discord is probably blocked on my host :/ 

Thanks

**Comment by naturecodevoid** [comment]
Feel free to make a feature request for proxy usage since that could probably be implemented.
