### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by MrHampterMC** [naturecodevoid/voicechat-discord#64]
Mod not even appear in modlist (MC fabric 1.21) and not creating any config file

**Screenshots**
![Minecraft_1 212024083208165516045](https://github.com/user-attachments/assets/31856b8a-db89-402c-a871-750eeb85b66c)
![mods2024083208165428279](https://github.com/user-attachments/assets/1f30d70f-fcb3-42b8-967d-5d146d0cae92)

Versions:
- Minecraft: 1.21
- Loader: fabric
- Simple Voice Chat: 2.5.20
- Simple Voice Chat Discord Bridge: 3.0.3/3.0.2

**Comment by naturecodevoid** [comment]
The mod goes in the server. It does nothing if you install it on your client.
