### ISSUE TITLE
Group support

### ISSUE THREAD

**Issue by MatadorProBr** [naturecodevoid/voicechat-discord#7]
Sometimes our server uses the group functionally if we are too far from each other but the problem is here: people using this plugin can't join the voice group using the "/voicechat join" since it says that "You don't have Voice Chat installed", maybe using the Voice Chat API, the plugin could pretend that the user has the Voice Chat mod installed and could make all the audio when he joins to the group be transmitted to others/to him too.

**Comment by naturecodevoid** [comment]
This is a known limitation of the plugin; Simple voice chat's API doesn't allow us to have an audio channel join a group. When I was first developing the plugin, I asked about emulating a player, but it's much better if I use an audio channel so it doesn't break stuff. (The API also doesn't allow me to spoof a player, so I would have to directly use Simple voice chat classes, which is just a terrible idea. There's a reason the API exists) I've asked the developers of Simple Voice Chat if something allowing us to do this can be added to the API, currently waiting for a response.
