### ISSUE TITLE
unable to start server with the latest version

### ISSUE THREAD

**Issue by onebeastchris** [naturecodevoid/voicechat-discord#9]
Hey, i'm trying to use this amazing mod on my 1.19.3 fabric server; but i'm getting an error when trying to launch it:
https://paste.gg/p/anonymous/bddd388c390946709ecb251478586442
It looks like it's potentially a missing dependancy? I'm not sure though; maybe you can help better

Let me know what else to provide/test. Running 1.19.3 fabric, and your mod is on 1.4.0

Thanks in advance!

**Comment by naturecodevoid** [comment]
Yes, it looks like snakeyaml is not included with Fabric. I will have to shadow snakeyaml in the Fabric jar. I am currently busy with other projects, but I will get to this as soon as possible.

In the mean time, I'm not sure if you'll be able to use the mod, sorry.

**Comment by onebeastchris** [comment]
no worries; thanks for the response!

**Comment by onebeastchris** [comment]
okay, seems like this is a compat. issue with floodgate-fabric; your mod seems to start just fine without it..
aaaaaaaa 

welp, sorry for not properly troubleshooting before opening this

**Comment by naturecodevoid** [comment]
I still consider this an issue with voicechat-discord, and it being a compat issue with floodgate explains  why I didn't run into it during testing. voicechat-discord should be compatible with floodgate, so I will still fix this in 1.5.0

**Comment by onebeastchris** [comment]
But this was fixed on Floodgate's side by relocating it's dependency on snakeyaml - your mod starts perfectly with and without floodgate now

Here the commit on floodgate-fabric: https://github.com/GeyserMC/Floodgate-Fabric/pull/85

**Comment by naturecodevoid** [comment]
Awesome, I thought it would be my responsibility to maintain compat with floodgate. I'm still going to make these changes to ensure this doesn't happen again
